minimumReleaseAge: 0
shamefullyHoist: true
strictPeerDependencies: false
nodeLinker: hoisted
blockExoticSubdeps: false

packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  electron-winstaller: true
  esbuild: false
  unrs-resolver: false
  vue-demi: false
