shamefullyHoist: true
strictPeerDependencies: false
nodeLinker: hoisted

packages:
  - .

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - sharp
