shamefullyHoist: true
strictPeerDependencies: false
nodeLinker: hoisted

packages:
  - .

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - sharp
