name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true
        
      - name: 💚 Build Nuxt app
        run: pnpm run generate

      - name: ✂️ Rebuild native modules
        run: |
          npm rebuild
          pnpm exec electron-rebuild
        
      - name: ⚛️ Make and publish artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec electron-forge publish
